//this is some commit of susham
package controller;

import jakarta.servlet.http.*;
import java.io.*;
import dao.MemberDao;
import model.Member;

/**
 * Servlet for adding a new member to the system.
 * Handles POST requests to create member records.
 */
public class AddMemberServlet extends HttpServlet {

    /**
     * Handles POST requests to add a new member.
     * @param request the HttpServletRequest object containing member data
     * @param response the HttpServletResponse object
     * @throws IOException if an I/O error occurs
     */
    protected void doPost(HttpServletRequest request, HttpServletResponse response) throws IOException {
        // Retrieve member details from request parameters
        String name = request.getParameter("name");
        String email = request.getParameter("email");
        String phone = request.getParameter("phone");
        String plan = request.getParameter("plan");

        // Create Member object (ID will be auto-generated by DB)
        Member m = new Member(0, name, email, phone, plan);
        MemberDao dao = new MemberDao();

        try {
            // Add member to database
            dao.addMember(m);
            // Redirect to view members page on success
            response.sendRedirect("viewMembers.jsp");
        } catch (Exception e) {
            e.printStackTrace();
            // Redirect back to add form on error
            response.sendRedirect("addMember.jsp?error=true");
        }
    }
}
